apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
