apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding
  namespace: homelab
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: linkding.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkding
            port:
              number: 80
