---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortliner-payment-db-secret
  namespace: shortliner
spec:
  encryptedData:
    DB_PASSWORD: AgC9FWZQj0pHKsNkiM5KSYdJ9zzMlLuzpga0jb06zJwFJILepCz9pedtzFSaaofb0++35+cO9BLgoHHcPj3goVy+B3GodwP3+BJHNgqcboM/AajQt791pLtlRJyC90+mUCt8Ww7yZQo65Y6qSsdQAmq0jLsu2ckTJsJiSbJHy1T75qNt7tComJylSbj4AwxNl/36ENb8cjLVpwRqb4yAyK8Wq1/B8Mr5TFjhMdrqMnKYvL2jXL897uFhxvTMg+8v5F3jKGYUiYIktocLrp3cdOb/nnFq87gQ1ez9GpX+Etpxb/TtcyPtGd26r0Fu259YYB/ZVGAapiqYDys61cOTx3lCF1OJ5mTY5VKqwO8mJh7Ph1lEOd7wvVgQfrqeJevIphe+5yDuskoNtVk9MHDAk1HKkKgNS07gPJWmwLJdTWmAo/CAzS2xExb8nqb2u83CZX+vXnC6pZ7hE1FsssxhC+K+JLEFPkkxQHfAMx+SQE93cVAmJ6rYXBegv155TnUnlnwYNeVYs/XRbSiMYmLHGtEfyi5jeP9dtPT3ZqsSvbG2VpVBXqq7Us3yYTH73hpV1fxYGR22PHTE5Mwhqx453OQaH9Jop6zfDfZH7+Qyzdr+TOPcCPYPWIXgIxlITW3/XSjUBB3YxHK0XwSOLWeDbhtKB5MiWmK9y/3uSjqrheQhL1H9r1r5OxA9juFOtiz9i/H5CBYyn0COqOTigi8bF/YDat8=
    DB_USER: AgA0fw6b7vOkIuLKdArVPzadFXMooYujqy2cQv5fvApTAUMzU9mT19UTHWmkgnwPPwKgJTKsrb6U+X9kbhdJMZxoA0q1JY6KK9KkoSw5NYELK0o/HhhA5oqZldenfsIyn98hrm2criyPo7AtJ3dZzehodWxY7npjersnPvBSFwv1XaJWbq583PqzvWJoLiUjYHyXyHTSnDnNtXa4l89IMNcGZv/2opxqbTQ0bqgE0D7uVoWQzXLI6ookmM5BaJ4VRRKaLGaULO7pfHYxZT0ZO1NA7N4YA9ahRDUSH891CkLu7I/b/md0lg1DEvLbWkmSwSHW0CkWNllqgXh9bC1SNvfcCKgDIYKHwt6V+xLXGLM1O8m+c7hDaMXciC5n+KFpPg/P2G428eCBSIGBmDXIh79XSoSvtU0y1mANxJNrbd8yexRI4fStzqAcjNnbu1Qgc8PMjJXp2n4bDveS9y9paMBfn9XtVTnEe1vUIyaCGYCKv2I+CD8ECFFN9nrboGJHenENY3FzGHrGX9/nDh5OttvxDfzPU+2lYvUkmHpqxSYbpeaBcm39+EUb1LOIuMuuaznofeP7/MytQq9CRk48m8UZCUsqFw/+1cCjDohmHrwt87MKqNXIIipRF6rNUUlcaoOu4NJhZzQf+DLPvTAQ4Sqfxuo8YH0Fpv5zobYnBCKgczoTXiAcXzB/GtUntMSjCy9Op8I+z4JjbHabqG0WvjheWtU=
  template:
    metadata:
      name: shortliner-payment-db-secret
      namespace: shortliner
    type: Opaque
