---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortliner-db-secret
  namespace: shortliner
spec:
  encryptedData:
    DB_PASSWORD: AgCpgTmtU4A2sTVv1zS9ocpi5Yf7MGXL6RSlOsFE5aASMQmyZVN3cwN4YChvOg0xnBnTau+GkUeXHrudHJqUHZreRmvbkNQNQXTrY/n3qRQSqnL/ej4jRXFS1ymlqEG4D82nIVaDeS7Oa2oEDvS43iE0KkSzcGKC2J43mJkolSgfxqdRS5fj14mqX34da1AJ6U8XGDtcJbSVWVNgx9/pZ6jOkp0vPo+74YKwlZIo9ivOA51lVTCh1n3cQILVNm9ZaZMFZ9KQtEhRFJrGqRdOkAl/L6TZYonQAZnVe7ykYWgTy2TVkG0BnCzFNQ5gJ8L057f360UnDMLlg5kl6jyk7pynmUWLz1cYeFeEB1UdzZO3c/nu1aVDaNueh+091//UaNj4Jf9MqzAswIrWeuUbNiLb/PyUkBAt29hLYKphH7tFLV/M+XOyO+RYTPibluRVSlS+iLSylwDP5eyzfwqTm1xPNKF1pT33MWMGdwtGVStpT1qF7bcuuQcV7nf9UmKNIWu/m+7TJ4rhKYPRZRLdUVmIo6E1hhjYflWblIyRr4hAIhf1nhBuljU0u7sOybd6zZGlawDJ8icWEhfVOkH3r8jGEjZQLJP3J7wFBbhE5cKRmXFy2PCwlwCKIy4pzbhQ+p0UUSCY5nPftRgAZy4JNV7dg0G07Xc+H+EvP/bhG7oW3jALIIJLViKtoELRha4mSSYuJXM5jjSetJi7
    DB_USER: AgBj+fIVqYiEc68IKo5sWfD2aNPiB0LjpBqvnBbDM2aegNBYILcyJ63xYaAAndwzweCZQaHAYtboZRPoGl9szmkxHjoTAZl+B85oLTx4WEXcpvS7t2XhK3zTqE7ViiZfBUIWOxYNvaGdvtd655enSQ7PNJ4NmNgpgPitDnTejg9qm+2PEmeWCoFmfMvPtF5/0plzETeaf0nFj8z1DuyyExfLIOkP7H+twEkPJwZOkLI/vtKt8oco7He80rSHy0DHyYUfhp6pltwt7nlj5RAxt77EET5rqivlU17qyX+DiGmu904prXCdpp5QLM18eS4ONkhfhi32j6L23dok+5LUuja0X4pfeMe0ba9Q+dgRK96lwFx9WXt2Rd/oVUB75rrnY6ZO8Jj/S+I0lsKSS3wKNC3BquHqdVBFE/vsjdVuZW9SPh83YO8MRajGMkOxBFqRBmQij2mPq85YAqGwpPyFSef+vUXtV2B/r5XLJC8Tseq8ea9vtMHL7LTjnDJGNPkRMKUp18EPscynO269/KtgHkTj1Dswrg0bs+CfFtSd4KQ68MpOz7hL+X7AB0cN0jw6+KFvvNlMY+q8+s9vC0PEh23duYVyLXmJJcvpQtSmyeKN/FHvQNJvemXVytlFF+5rZg7mcaFiZTmH5k7FY3qCX97f2i+lSsNDCdSOnqw5VKuGL1X8B5S61TeSpRPeHgD2H/0iFR1rJn1UbMIi
  template:
    metadata:
      name: shortliner-db-secret
      namespace: shortliner
    type: Opaque
