---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortliner-analytics-db-secret
  namespace: shortliner
spec:
  encryptedData:
    DB_PASSWORD: AgBxWXJh2RWiW5iVuRT5Md7n3KFNaDFlLbPM6ZFypA9EApu//jvg8b67U5sSQzfd5f8AkPMBcTIQuB79baMyBE2J87Vl3eYp2BCZci+jIrGHowH0mv1c2DtQtM+qjtkGCiTEJKUUBrFPOU9zMBEcW13v1hg3au91D8ZFpge3Uk41f1kYMn+E8vc+lFRVBhDwMveLVVN+PNKJhTTGowFjwJkj/ph9/YB2Tyn/q1WeBcCX1dMnZ2k5kQ7M2ToLa4oDFnYu6CxJ5AWAuskqdN2z+YkkH3ex0k5lVGO3ylAvY83F32xX1tBqK0IdsK8TX9p2SiEzLFFwuhVVYgzRvqCdVrNpN79XP4qQ9BMKPOcwsKGOkQ+NXrMBl9ocEy1Vkn7ADlDjfT19uVpV6ozrrQbsYaWuJ+L4HMIFcZTcQ2mH+KPfzTcqSotlycNG+RmYUDNuwVDpuS5PB/PdQ/qRk0mTcjWsA2R6S8fh/on4T+ZonHMtPf+qj8ycFZwFH1X20n9DOWcZlIKx76QrRMTbUuVS0yolP3mBvuq3I+vOzyDoX55LAxx20rt/CvU/rRi+6uc7roy3hbevWpN35kQPkfM/Cswi6qJzWdhWqv9/HEisYWL90HAybozdrof87wFg0eRrPwcGctW4MJhh08zfF48Mrmbkn/bD1FZmGDo0UIhyaa2bESF3BrmC3gPjRQF2nNkgmRvuIg75Mi6YpRGPLA/gnmverfvqHg==
    DB_USER: AgA6pWKW5gSz0DF+oAtft7TrbDbcwrzx7rs9weUs/n1fLue7Ia18xThnSHC8QiwCoeMD1qOfpzPzsaC7m2ptqXcaq7kSXLCTNQfA6ZdFTZe33WjG/kpPqfNG/W2V7TH6MeOdzgABAgIq6D4bqoQqnQZ4lrebpHcKihxMsCAU57HY7/gn/g9f8OEXH4LHIAcjbeyBCMnKFYFf59dxbbbtMuGb270l5pX/QBYutLzCPC1MhaqH8U4dAjqnPX3Y+bXls84qAT9bjqmYU23yjzEFsaJ1Ryndm+UkhfwikuEeW+AfB40IvOg+W29pnEGoSnFvZUFnszToJk7ZcK4BFbbA6jBJxQOuwOjjwfvrC8CMn88i3zoNrK6SL/11SqaPUDiZL7+Cvb0FlxoSdg+N86/E48YJaX3DHDXTj+UW6l4azj9RFFDPy4lkb3nUgtKXPZWULKujTPgz2klnfPli9kJ4Qg868N6ukoQi3KkXfphJ5keyzS3yDPI/eyjXEsxn6Nq21g4XlDi94X3x5tvgRJO25lK523j0XIUW7FVTnzSbGUiiqTOBAY8A+0qBD7G4X6VvnVu1pTqq3drc9l6pp8J+wh0wVfRl0Som0Pu9muWUT9EVRtbeh5MOoyPt4KAlCNjcJM7r4SQBDHWRIHHnlddwOTv+QD1s7DnYrY5wq5WF429a7DzSGiLSrbL+C9JfDjU0iQhEW4M7EwF9R+hahJfAOhleZp+zVw==
  template:
    metadata:
      name: shortliner-analytics-db-secret
      namespace: shortliner
    type: Opaque
