---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-secrets
  namespace: homelab
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCS3cez/06bwgtUYojv1gbnnYjW05K8C0YP+QcDn0b9AzmkzRJu3DFYuJl69bbYy4LTTQuqP1nNycl35Wtv8XocpbBRmHy1OjJzB6b3rGKFooExBdz+vJ2Xj3J1jEOT3wLXHKMi3mV3JaRg6Ix9TyTNz0QwTMYsPEPz+3y1OXCRazKpDvP28zFfpmYBnjT8rTD7QXxH42xO+dlRjsOPxEkiH4q9lVbsTTvLIOYRoPW9WKpvPk6PY4KVFtFfxjINEalQ2ToDzxWb9sT+ZPhwnWobFOlNtOI5G9WflAD6Vkprrmkq81UlhmDCf9Ek1HJxGHPDZiWySXJl09S0Dxkw1tSvBcwjrDNcxluQbQmBCusA7JonoQ0+Rm8ziLdOKta/akYOaa2DQVOuZVUOPdx4nbd97p9k/uRl4p2+HkQCBNJgrSMTsY0ORuIpPG2SyxJSRjk/uLJI2SvvZNfNuzG47rgXdMPA5xPh6kWFwEZQkKwNI9k5cPoa7lIlgw7lA9SU7jQhLOO3Gjli6z8QcFgmXT4ZzmAqg3+1Cb23BVPM4oTFGJnvoZD2LNWW5pZ2ksdavfN9OL7tPEbJsAl36Yt+2GL2LSdz48DAuqmMC833YbDKxhlvgNyxwIxumud42oDtVDuLdxfAfR9OSIr3O2PHuLVb8Jp61PP2Zx6EK0hcf0lQ8TkQGmOmcghEFFTgAA3KKUiI1VwyoF4=
  template:
    metadata:
      name: mealie-secrets
      namespace: homelab
    type: Opaque
