apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: homelab
  labels:
    app: mealie
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.9.2
          ports:
            - containerPort: 9000
          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL                       
            readOnlyRootFilesystem: false

          env:
            - name: ALLOW_SIGNUP
              value: "true"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Warsaw"
            - name: BASE_URL
              value: "http://mealie.local"
            
            # Baza danych
            - name: DB_ENGINE
              value: "postgres"
            - name: POSTGRES_USER
              value: "mealie"
            - name: POSTGRES_DB
              value: "mealie"
            - name: POSTGRES_SERVER
              value: "192.168.0.78"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data
