---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shortliner-gateway-keycloak
  namespace: shortliner
spec:
  encryptedData:
    KEYCLOAK_CLIENT_SECRET: AgAiAL3R2CxMxsSXYSnK3wZW7WYj1vTlbgzUrTgj1ge9M1ANZiZRJH2l+ZHWE82yme4kwKzDlqRtN3ZufmkA0WoCRCSJqxEPRsYDm88t5yA+gHcnqGg69q7EFTypqZw6GqupYuDjSLME7hTp6NcZ9BYSKM2dtXjSStHvXz+5a12mKvIKVerQ1Y//39dmYp3TxjNOXHyWEb/V7xr4c++ntlRVPSBRLjm03VY0MMv/2i89YDZgu9FC6Id0hcP8o5ZiFKLNa1fMnVT3Nm0FvYKs5lYGPZDk4rwZjyrkeg9eIpkwfj6/vM5bTSLk75rdOhp4l+mE+NAD+rPDckLg+QcxVaqPSTmwUlQ7belErUQyVIddZ50NTP/ZNEVkd9ijmHYghO6Ax3gF8n86thFxS0oyCAWecUMwmjmMCyCBb3GYvxrOd6h5IpuTrD4dyKGp3XaZmnXGh7ytgkapvsv+MA8tVeEeLJbnu49FhIh1sVHv214p/YhcVQmg/Eu63bBzqM/g+d+clkzCfrsPCkwt7LHQaO5/j9DMKEy6vG5nNimCIrHBhoiGSVchGvKlpEbF4LDEo8I0g2EqJd1682DVY53at4ccLuiaSizK+TxfWQKhH1+8ThJ6jSCTjzGxQl4Kuicucpq6hk92thdWoU0oMKr8qAhG6JBa8DXESJ6PHQ58OogCGy1r2oRq3PtSvCqxKTbdWBuZG4mpgfBKDmXv0zMaR2VtwqYm4fXj6ghavTCD88CMSSde6wA+bmRm2GcSvszta+cFxhMD9xLznWBnMbOIqtWqwQZtDBD9rMtj31vZNVcfDdTXkQm14w==
  template:
    metadata:
      name: shortliner-gateway-keycloak
      namespace: shortliner
