---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgC03RvfO/QnIYSJi0XZ8PVROTRRE5tYVOhyjz/uADgcXNvSmp18qhzaQSxZ9enJgs1oFRDGh+EwbhLvSB5t44f7DAotgRUKDXQMmo7W0Zc+nYDxwXyuNLF4b6lKy7km0Hi6hOcfVaMurkTI6E388Ms8CHzio36MeDjVq8gyaW63F24rn2qTLXUaaIUSaEhvQBV0W7bq3udsrk5nIS8twAytchVJgFmtD31GXBR0JGhzdhLGV387SSI/RIG3h9ISa9+coPkZlDHuek+PKjPHK30PFZ7yxD7qsXusgyr8S2i6KM5Nv7GQJK01wvdQn6ZT3Od8h1It869BEbDyTHfYiMNmbIDIsL813q+GkAiG9GP2aGCr+IPq1FR+o86lcdNDyVy7wu1H05aUBmx9Wmwmi27jlc8iJCF5a3Jwtfh7O+vZO7H8p6BFr5Knc2d2UQH4jr/oszBlW5W2mFvYyaxs4GoIL4wbOOlzGa4P/HppusaD5mvinbm+S2aqJzmGjqpAdiv6jkgpf15iW/ms7Bpzpq3X1z3UXJYFTE31wG/oCg+6y1IkmxsvHfog/eEfEMEy+IlwKO9FjS7zzlTFZeIZfGkQLY2Tcv3q8q7vpr50B92gyaTSPNK+9REX4RE1yubSezxd6/mKEs3JY6MpT4gLyzquTgYue4j6vGrTVNn4SFMoMMP+F+UjIsLr597TH8iDTaxUzcousSQwmXchvz4IhGu7Qdc6xfZfPKg=
  template:
    metadata:
      name: keycloak-admin
      namespace: keycloak
