---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    DB_PASSWORD: AgCeRhZZNLxC/alakEUTzoxSvhwfZsPAEZ+LDGoxY5LOLbVIyEF1OUDIzfGrPJlURJDBinzTk1NCqdVYiDopPCZfH9IrgaZnpOTAM9gKZspYeq3dwMzwP7JUPbnPP1OPxM62GMJL5XEUq+7SUvsAXbt/vLYxngC0nW6fPYVkIV1IS3/CbkWjZqg3jmAwPdjizSTpyqPf5DPljNDkVcYh7BB2fq3Ny6F4YPw7FrXgwaPA0ZK/wqHvmPEj0Wb/eXFjfomQtSB4waIDHk1SepF0FvhgsUoIKR7BiENNzPSEfMxgo/Qqbz1ha7oLbIePtW1xLFV8cgvQAX93IIXBAF9MW4FBTUECArZ+7S0lqVMdD41hYEO5M5ByFaqMRiUeq4luvaXki7+hAS+CzVUnF5dRv+bqINAgmLWVCR/KgWy+JfQCkq1liRgDiz2NduxIHNESuk0VSps0UPBgAr1pqIFXfeDjDc7z6mfOfl8LZ27OdWyMcCSeJyYUgAOr1dXYzr3U0Ja74YLtFM4FuXjsdE2VQv3WLYpHMsjUYKmWBTqBjLlrcmrLQVKmYafFgxKdO+TWlUWkvj/ixIXMfoCBr3quzGpAkR5VIaPuRkXGH1MnmOMehtf195b3hfafmqFV8sJmEllTgNDKz2yRw0qwtLoTiBxFRMsWQpyBOzYdvuru1gFs+gnhfWDqrJZi23UQ/qwBe5LAXu64sW+wWAk9FXMHDbdAmKI2bKHZU2Q=
    DB_USER: AgC3nsjT3sEMZND8H7MgWNw0660jYGGbw6dl4pM6HdsLW141BuzSpdJrd0BfFQhfk3SX0prIVE+tLzCkhwMFa/msnTboJl4gL/GWUDGY9EWVEOx3ThzYLKhZmmbF8ozCsT/+D+TSwVVGo4ZgIzQX0xwtOVMwCFxq0adYafUGKNIr9R+mjF7ntjARwh95epQPUbpS56ToDlgMJ4JlxNyFWT9rJbKv22+EzERhUuAFjlJK5/hI8IqK89Go+TGSOLIFJNxbyevTezv6gL0x87gPu3gefNyzNkGsYkgQMDqAcadIOuvZDoMil4eeGABA7aunjqntV4ZJgZrgvAiabcav+x9njFSqsm52lto8aAlyJcI/UtU3urKQ2foq6ZLPpYBDaXZQeB5yHi+GdlVP08RataMPnkYom+rEgpNbX92Aiq5VbrRigKW2LEDLcm9SubPVTsdF/83AQNGv/llzVq5Peu8YQLBkzSFk0NfB2O08Kj6Fa1KIfFmOMC9/PJNd+fxoXzJtSi/Z416c59+7qK7rAF5DSsutdTqI9VuSIAIT15wxOweshJFeD2QvslQNembYaf8EO+JIbVKkVr/344ugOI4DN9Cqh9uIDm/djW4WvvtO8/PW8ctEQ95OZ6DEIU0eOvelwiF9FyyGdzXQLmHW5Nu2PiYvpme+ajuNj2wd8NOVWQDATzFzx/vGil47BA9VrlrQz3MIdKfI6A==
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
