apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: shortliner.payments.completed
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    min.insync.replicas: 1
